print("1. Mix 500g of Flour, 10g Yeast and 300ml Water in a bowl.")
print("2. Knead the dough for 10 minutes.")
print("3. Add 3g of salt.")
print("4. Leave the rise for 2 hours.")
print("5. Bake at 200 degree C for 30 minutes.")